import {
  FileText, Megaphone, Palette, Receipt, Users, Workflow, type LucideIcon,
} from "lucide-react";
import type { FeatureFlagKey } from "@/lib/featureFlags";
import type { WorkspacePermission } from "@/lib/permissions";

export type CreateAction = {
  id: string;
  label: string;
  icon: LucideIcon;
  /** Where the real creation control already lives - the Create menu never
   * builds a second form, it just launches the existing one. */
  to: string;
  flag?: FeatureFlagKey;
  permission?: WorkspacePermission;
};

// Every entry here reuses an existing creation flow that already lives on
// its destination page - "Add customer" and "Create document" are
// deliberately absent because neither has a real standalone creation flow
// in StabiFlow today (customers arrive via lead conversion; documents are
// generated by Business Studio, not authored directly) and this menu must
// never route someone into a flow that doesn't exist.
export const CREATE_ACTIONS: CreateAction[] = [
  { id: "lead", label: "Add lead", icon: Users, to: "/app/leads", flag: "module.leads", permission: "lead.create" },
  { id: "post", label: "Create post", icon: FileText, to: "/app/content/scheduled", flag: "module.content", permission: "content.create" },
  { id: "campaign", label: "Create campaign", icon: Megaphone, to: "/app/campaigns/new", flag: "module.campaigns", permission: "campaign.create" },
  { id: "creative", label: "Create creative", icon: Palette, to: "/app/creative-studio", flag: "module.creative_studio", permission: "content.create" },
  { id: "automation", label: "Create automation", icon: Workflow, to: "/app/automations", flag: "module.automations", permission: "automation.create" },
  // Reserved: module.invoicing is permanently off until the dedicated
  // invoicing branch ships (see src/lib/navigation.ts) - these never
  // appear until then, and no /app/invoices or /app/quotes route exists yet.
  { id: "invoice", label: "Create invoice", icon: Receipt, to: "/app/invoices", flag: "module.invoicing" },
  { id: "quote", label: "Create quote", icon: Receipt, to: "/app/quotes", flag: "module.invoicing" },
];

export type CreateActionFilter = {
  isEnabled: (flag: FeatureFlagKey) => boolean;
  hasPermission: (permission: WorkspacePermission) => boolean;
};

export function availableCreateActions(actions: CreateAction[], filter: CreateActionFilter): CreateAction[] {
  return actions.filter((a) => (!a.flag || filter.isEnabled(a.flag)) && (!a.permission || filter.hasPermission(a.permission)));
}
